{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Distributed Training with TorchX and Ray\n",
    "\n",
    "Training models on large clusters is challenging for a few reasons\n",
    "1. Need to setup an infrastructure\n",
    "2. Need a way to submit jobs like distributed training scripts\n",
    "3. Need a way to monitor the status jobs, aggregate logs from several machinees and collect artifacts when model training is done\n",
    "\n",
    "With the new torchX Ray scheduler this process has been dramatically simplified."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Ray scheduler for torchX is an experimental feature\n",
    "! pip install git+https://github.com/pytorch/torchx.git@raydriver -q\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "! pip install \"ray[default]\" -q "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Infrastructure setup\n",
    "\n",
    "Ray provides a feature called `ray up cluster.yaml` which given a YAML file and access to your cloud credentials (e.g: AWS, GCP, Azure) will go ahead and setup an infrastructure for you. \n",
    "\n",
    "Let's take a look at what the script looks like\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "# An unique identifier for the head node and workers of this cluster.\n",
      "cluster_name: gpu-docker\n",
      "\n",
      "min_workers: 1\n",
      "max_workers: 4\n",
      "\n",
      "# The autoscaler will scale up the cluster faster with higher upscaling speed.\n",
      "# E.g., if the task requires adding more nodes then autoscaler will gradually\n",
      "# scale up the cluster in chunks of upscaling_speed*currently_running_nodes.\n",
      "# This number should be > 0.\n",
      "upscaling_speed: 1.0\n",
      "\n",
      "# This executes all commands on all nodes in the docker container,\n",
      "# and opens all the necessary ports to support the Ray cluster.\n",
      "# Empty string means disabled.\n",
      "docker:\n",
      "  image: \"rayproject/ray-ml:latest-gpu\"\n",
      "  # image: rayproject/ray:latest-gpu   # use this one if you don't need ML dependencies, it's faster to pull\n",
      "  container_name: \"ray_nvidia_docker\" # e.g. ray_docker\n",
      "\n",
      "\n",
      "# If a node is idle for this many minutes, it will be removed.\n",
      "idle_timeout_minutes: 5\n",
      "\n",
      "# Cloud-provider specific configuration.\n",
      "provider:\n",
      "  type: aws\n",
      "  region: us-west-2\n",
      "  # Availability zone(s), comma-separated, that nodes may be launched in.\n",
      "  # Nodes are currently spread between zones by a round-robin approach,\n",
      "  # however this implementation detail should not be relied upon.\n",
      "  availability_zone: us-west-2a,us-west-2b\n",
      "  security_group:\n",
      "    GroupName: dashboard_group\n",
      "    IpPermissions:\n",
      "      - FromPort: 20002\n",
      "        ToPort: 20002\n",
      "        IpProtocol: TCP\n",
      "        IpRanges:\n",
      "          - CidrIp: 0.0.0.0/0\n",
      "\n",
      "\n",
      "# How Ray will authenticate with newly launched nodes.\n",
      "auth:\n",
      "  ssh_user: ubuntu\n",
      "# By default Ray creates a new private keypair, but you can also use your own.\n",
      "# If you do so, make sure to also set \"KeyName\" in the head and worker node\n",
      "# configurations below.\n",
      "#    ssh_private_key: /path/to/your/key.pem\n",
      "\n",
      "# Tell the autoscaler the allowed node types and the resources they provide.\n",
      "# The key is the name of the node type, which is just for debugging purposes.\n",
      "# The node config specifies the launch config and physical instance type.\n",
      "available_node_types:\n",
      "  # GPU head node.\n",
      "  ray.head.gpu:\n",
      "    # worker_image: rayproject/ray:latest-gpu   # use this one if you don't need ML dependencies, it's faster to pull\n",
      "    # The node type's CPU and GPU resources are auto-detected based on AWS instance type.\n",
      "    # If desired, you can override the autodetected CPU and GPU resources advertised to the autoscaler.\n",
      "    # You can also set custom resources.\n",
      "    # For example, to mark a node type as having 1 CPU, 1 GPU, and 5 units of a resource called \"custom\", set\n",
      "    # resources: {\"CPU\": 1, \"GPU\": 1, \"custom\": 5}\n",
      "    resources: {}\n",
      "    # Provider-specific config for this node type, e.g. instance type. By default\n",
      "    # Ray will auto-configure unspecified fields such as SubnetId and KeyName.\n",
      "    # For more documentation on available fields, see:\n",
      "    # http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.ServiceResource.create_instances\n",
      "    node_config:\n",
      "      InstanceType: p2.xlarge\n",
      "      ImageId: ami-0a2363a9cff180a64 # Deep Learning AMI (Ubuntu) Version 30\n",
      "      # You can provision additional disk space with a conf as follows\n",
      "      BlockDeviceMappings:\n",
      "        - DeviceName: /dev/sda1\n",
      "          Ebs:\n",
      "            VolumeSize: 100\n",
      "      # Additional options in the boto docs.\n",
      "  # CPU workers.\n",
      "  ray.worker.default:\n",
      "    # Override global docker setting.\n",
      "    # This node type will run a CPU image,\n",
      "    # rather than the GPU image specified in the global docker settings.\n",
      "    docker:\n",
      "      worker_image: \"rayproject/ray-ml:latest-cpu\"\n",
      "    # The minimum number of nodes of this type to launch.\n",
      "    # This number should be >= 0.\n",
      "    min_workers: 1\n",
      "    # The maximum number of workers nodes of this type to launch.\n",
      "    # This takes precedence over min_workers.\n",
      "    max_workers: 2\n",
      "    # The node type's CPU and GPU resources are auto-detected based on AWS instance type.\n",
      "    # If desired, you can override the autodetected CPU and GPU resources advertised to the autoscaler.\n",
      "    # You can also set custom resources.\n",
      "    # For example, to mark a node type as having 1 CPU, 1 GPU, and 5 units of a resource called \"custom\", set\n",
      "    # resources: {\"CPU\": 1, \"GPU\": 1, \"custom\": 5}\n",
      "    resources: {}\n",
      "    # Provider-specific config for this node type, e.g. instance type. By default\n",
      "    # Ray will auto-configure unspecified fields such as SubnetId and KeyName.\n",
      "    # For more documentation on available fields, see:\n",
      "    # http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.ServiceResource.create_instances\n",
      "    node_config:\n",
      "      InstanceType: m5.large\n",
      "      ImageId: ami-0a2363a9cff180a64 # Deep Learning AMI (Ubuntu) Version 30\n",
      "      # Run workers on spot by default. Comment this out to use on-demand.\n",
      "      InstanceMarketOptions:\n",
      "        MarketType: spot\n",
      "        # Additional options can be found in the boto docs, e.g.\n",
      "        #   SpotOptions:\n",
      "        #       MaxPrice: MAX_HOURLY_PRICE\n",
      "      # Additional options in the boto docs.\n",
      "\n",
      "# Specify the node type of the head node (as configured above).\n",
      "head_node_type: ray.head.gpu\n",
      "\n",
      "# Files or directories to copy to the head and worker nodes. The format is a\n",
      "# dictionary from REMOTE_PATH: LOCAL_PATH, e.g.\n",
      "file_mounts: {\n",
      "  #    \"/path1/on/remote/machine\": \"/path1/on/local/machine\",\n",
      "  #    \"/path2/on/remote/machine\": \"/path2/on/local/machine\",\n",
      "}\n",
      "\n",
      "# List of shell commands to run to set up nodes.\n",
      "# NOTE: rayproject/ray:latest has ray latest bundled\n",
      "setup_commands: []\n",
      "# - pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp36-cp36m-manylinux2014_x86_64.whl\n",
      "# - pip install -U \"ray[default] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl\"\n",
      "\n",
      "# Custom commands that will be run on the head node after common setup.\n",
      "head_setup_commands:\n",
      "  - pip install boto3==1.4.8  # 1.4.8 adds InstanceMarketOptions\n",
      "\n",
      "# Custom commands that will be run on worker nodes after common setup.\n",
      "worker_setup_commands: []\n",
      "\n",
      "# Command to start ray on the head node. You don't need to change this.\n",
      "head_start_ray_commands:\n",
      "  - ray stop\n",
      "  - ulimit -n 65536; ray start --dashboard-port 20002 --dashboard-host=0.0.0.0 --include-dashboard True --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml\n",
      "\n",
      "# Command to start ray on worker nodes. You don't need to change this.\n",
      "worker_start_ray_commands:\n",
      "  - ray stop\n",
      "  - ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076\n"
     ]
    }
   ],
   "source": [
    "! cat ray_cluster.yaml"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Understanding `ray_cluster.yaml`\n",
    "\n",
    "1. docker: provides link to the docker images that will be setup on the cluster which is an easy way to setup your dependencies\n",
    "2. provider: determine your cloud provider and region\n",
    "3. GroupName: jobs will be submitted against a Ray endpoint called the dashboard\n",
    "4. resources: to determine the number of CPUs and GPUs allocated to each node - try making this number bigger\n",
    "5. node_config: the machine instance type, AMI and options for spot instances for cheaper training\n",
    "5. commands to start on worker or head nodes: you don't need to change these, they're what make it easier for you to setup your infra instead of \n",
    "\n",
    "To learn more about available options make sure to visit https://docs.ray.io/en/latest/cluster/config.html\n",
    "\n",
    "In this tutorial we're going to be running on AWS but running on a different cloud provider should just be a simple config change"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Setup aws cli\n",
    "\n",
    "Since we're running on aws you're going to need to \n",
    "1. Install the AWS cli https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html\n",
    "2. Configure the AWS cli by running `aws configure` https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html\n",
    "\n",
    "And now we can start doing deep learning stuff"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import ray"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "    SSH still not available \u001b[2m(SSH command failed.)\u001b[22m\u001b[26m, retrying in \u001b[1m5\u001b[22m\u001b[26m seconds.\n"
     ]
    }
   ],
   "source": [
    "# Having some issues with ray up taking forever\n",
    "# Stop existing instances of Ray\n",
    "! ray stop --force\n",
    "\n",
    "# Setup ray cluster\n",
    "# This may take a few minutes - Ray will retry several ssh connections before succeeding\n",
    "! ray up ray_cluster.yaml -y"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Writing ray_simple.py\n"
     ]
    }
   ],
   "source": [
    "%%writefile ray_simple.py\n",
    "def main() -> None:\n",
    "    print(\"hello\")\n",
    "    return\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[32mStopped all 2 Ray processes.\u001b[39m\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "! ray stop --force"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[37mLocal node IP\u001b[39m: \u001b[1m172.31.51.124\u001b[22m\n",
      "2022-01-26 01:00:32,703\tINFO services.py:1338 -- View the Ray dashboard at \u001b[1m\u001b[32mhttp://127.0.0.1:8265\u001b[39m\u001b[22m\n",
      "\n",
      "\u001b[32m--------------------\u001b[39m\n",
      "\u001b[32mRay runtime started.\u001b[39m\n",
      "\u001b[32m--------------------\u001b[39m\n",
      "\n",
      "\u001b[36mNext steps\u001b[39m\n",
      "  To connect to this Ray runtime from another node, run\n",
      "  \u001b[1m  ray start --address='172.31.51.124:6379' --redis-password='5241590000000000'\u001b[22m\n",
      "  \n",
      "  Alternatively, use the following Python code:\n",
      "    \u001b[31mimport\u001b[39m\u001b[26m ray\n",
      "    ray\u001b[31m.\u001b[39m\u001b[26minit(address\u001b[31m=\u001b[39m\u001b[26m\u001b[33m'auto'\u001b[39m\u001b[26m, _redis_password\u001b[31m=\u001b[39m\u001b[26m\u001b[33m'5241590000000000'\u001b[39m\u001b[26m)\n",
      "  \n",
      "  To connect to this Ray runtime from outside of the cluster, for example to\n",
      "  connect to a remote cluster from your laptop directly, use the following\n",
      "  Python code:\n",
      "    \u001b[31mimport\u001b[39m\u001b[26m ray\n",
      "    ray\u001b[31m.\u001b[39m\u001b[26minit(address\u001b[31m=\u001b[39m\u001b[26m\u001b[33m'ray://<head_node_ip_address>:10001'\u001b[39m\u001b[26m)\n",
      "  \n",
      "  \u001b[4mIf connection fails, check your firewall settings and network configuration.\u001b[24m\n",
      "  \n",
      "  To terminate the Ray runtime, run\n",
      "  \u001b[1m  ray stop\u001b[22m\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "! ray start --head"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[37mLocal node IP\u001b[39m: \u001b[1m172.31.51.124\u001b[22m\n",
      "2022-01-26 01:00:52,490\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158852.490743112\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158852.490742074\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:00:53,492\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158853.492577356\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158853.492576516\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:00:54,494\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158854.494567779\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158854.494566951\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:00:55,496\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158855.496552682\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158855.496551615\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:00:56,498\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158856.498593812\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158856.498592995\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:00:57,500\tERROR node.py:1286 -- ERROR as <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158857.500569298\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158857.500568492\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:00:59,503\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158859.503125358\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158859.503124293\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:00,505\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158860.505186768\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158860.505185922\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:01,507\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158861.507147278\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158861.507146507\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:02,509\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158862.509133265\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158862.509132399\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:03,511\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158863.511118215\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158863.511117350\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:04,513\tERROR node.py:1286 -- ERROR as <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158864.513115012\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158864.513114138\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:06,515\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158866.515669612\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158866.515668703\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:07,517\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158867.517660240\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158867.517659431\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:08,519\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158868.519622682\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158868.519621924\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:09,521\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158869.521617147\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158869.521616241\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:10,523\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158870.523593383\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158870.523592558\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:11,525\tERROR node.py:1286 -- ERROR as <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158871.525564577\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158871.525563770\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:13,528\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158873.528120096\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158873.528119014\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:14,530\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158874.530115921\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158874.530114960\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:15,532\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158875.532103821\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158875.532102974\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:16,534\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158876.534072687\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158876.534071896\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:17,536\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158877.536060280\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158877.536059438\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:18,538\tERROR node.py:1286 -- ERROR as <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158878.538062088\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158878.538061155\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:20,540\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158880.540616897\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158880.540615959\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:21,542\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158881.542683560\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158881.542682566\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:22,544\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158882.544668708\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158882.544667847\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:23,546\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158883.546679270\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158883.546678296\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:24,548\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158884.548659692\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158884.548658469\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:25,550\tERROR node.py:1286 -- ERROR as <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158885.550639475\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158885.550638587\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:27,553\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158887.553072390\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158887.553071274\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:28,555\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158888.555112164\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158888.555111190\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:29,557\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158889.557127109\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158889.557126179\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:30,559\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158890.559089785\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158890.559088865\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:31,561\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158891.561095988\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158891.561081223\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:32,563\tERROR node.py:1286 -- ERROR as <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158892.563090949\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158892.563090057\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:34,565\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158894.565631064\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158894.565630116\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:35,567\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158895.567636178\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158895.567635372\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:36,569\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158896.569637997\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158896.569637043\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:37,571\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158897.571640152\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158897.571639214\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:38,573\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158898.573634934\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158898.573633770\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:39,575\tERROR node.py:1286 -- ERROR as <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158899.575630800\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158899.575629926\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:41,578\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158901.578189277\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158901.578188420\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:42,580\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158902.580261014\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158902.580260168\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:43,582\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158903.582287131\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158903.582282029\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:44,584\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158904.584282849\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158904.584281972\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:45,586\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158905.586286336\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158905.586285434\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:46,588\tERROR node.py:1286 -- ERROR as <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158906.588299895\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158906.588299067\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:48,591\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158908.590891138\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158908.590890155\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:49,593\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158909.592945488\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158909.592944567\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:50,595\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158910.594966521\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158910.594965657\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:51,597\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158911.596967832\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158911.596966841\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:52,599\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158912.598977252\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158912.598976281\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:53,601\tERROR node.py:1286 -- ERROR as <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158913.600946674\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158913.600945712\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:55,603\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158915.603508126\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158915.603507292\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:56,605\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158916.605542282\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158916.605541406\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:57,607\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158917.607530949\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158917.607530028\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:58,609\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158918.609507537\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158918.609506725\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:01:59,611\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158919.611467519\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158919.611466596\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:00,613\tERROR node.py:1286 -- ERROR as <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158920.613465284\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158920.613464370\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:02,616\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158922.615885660\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158922.615884418\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:03,618\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158923.617889067\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158923.617888130\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:04,620\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158924.619904057\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158924.619903185\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:05,621\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158925.621536857\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158925.621536003\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:06,623\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158926.623483642\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158926.623482754\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:07,625\tERROR node.py:1286 -- ERROR as <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158927.625452516\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158927.625451420\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:09,628\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158929.627997796\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158929.627996942\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:10,630\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158930.630011011\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158930.630010119\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:11,632\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158931.632005548\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158931.632004671\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:12,634\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158932.633987287\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158932.633986461\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:13,636\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158933.635988272\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158933.635987405\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:14,638\tERROR node.py:1286 -- ERROR as <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158934.638117652\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158934.638116809\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:16,640\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158936.640704664\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158936.640703793\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:17,642\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158937.642807837\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158937.642806885\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:18,645\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158938.644827166\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158938.644826231\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:19,647\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158939.646903698\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158939.646902738\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:20,649\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158940.648938281\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158940.648937347\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:21,651\tERROR node.py:1286 -- ERROR as <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158941.651026885\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158941.651025879\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:23,653\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158943.653656571\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158943.653655610\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:24,655\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158944.655768472\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158944.655767514\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:25,657\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158945.657573574\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158945.657572676\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:26,659\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158946.659632995\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158946.659632069\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:27,661\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158947.661654441\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158947.661653114\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:28,663\tERROR node.py:1286 -- ERROR as <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158948.663711527\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158948.663710642\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:30,666\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158950.666295072\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158950.666294278\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:31,668\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158951.668412318\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158951.668411294\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:32,670\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158952.670458670\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158952.670457633\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:33,672\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158953.672517034\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158953.672516086\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:34,674\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158954.674567165\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158954.674566269\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:35,676\tERROR node.py:1286 -- ERROR as <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158955.676628433\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158955.676627493\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:37,679\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158957.679115235\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158957.679113727\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:38,681\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158958.681303398\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158958.681302509\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:39,683\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158959.683368187\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158959.683367119\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:40,685\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158960.685494270\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158960.685493077\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:41,687\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158961.687652290\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158961.687651468\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:42,689\tERROR node.py:1286 -- ERROR as <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158962.689703477\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158962.689702431\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:44,692\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158964.692302167\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158964.692301333\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:45,694\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158965.694414907\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158965.694414060\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:46,696\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158966.696472428\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158966.696471598\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:47,698\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158967.698522502\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158967.698521632\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:48,700\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158968.700575157\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158968.700574345\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:49,702\tERROR node.py:1286 -- ERROR as <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158969.702647329\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158969.702646495\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:51,705\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158971.705251622\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158971.705250612\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:52,707\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158972.707332826\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158972.707331812\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:53,709\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158973.709418748\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158973.709417933\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:54,711\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158974.711476680\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158974.711475914\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:55,713\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158975.713539767\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158975.713538782\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:56,715\tERROR node.py:1286 -- ERROR as <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158976.715589060\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158976.715588311\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:58,718\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158978.718197433\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158978.718196562\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:02:59,720\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158979.720313980\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158979.720312994\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:03:00,722\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158980.722392562\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158980.722391728\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:03:01,724\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158981.724454738\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158981.724453931\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:03:02,726\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158982.726519085\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158982.726518144\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:03:03,728\tERROR node.py:1286 -- ERROR as <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158983.728592982\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158983.728592050\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:03:05,731\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158985.731184735\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158985.731183813\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:03:06,733\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158986.733299509\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158986.733298561\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:03:07,735\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158987.735384722\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158987.735383582\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:03:08,737\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158988.737462596\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158988.737461717\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:03:09,739\tERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158989.739528361\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158989.739527524\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "2022-01-26 01:03:10,741\tERROR node.py:1286 -- ERROR as <_InactiveRpcError of RPC that terminated with:\n",
      "\tstatus = StatusCode.UNAVAILABLE\n",
      "\tdetails = \"failed to connect to all addresses\"\n",
      "\tdebug_error_string = \"{\"created\":\"@1643158990.741603301\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3093,\"referenced_errors\":[{\"created\":\"@1643158990.741602485\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}\"\n",
      ">\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/bin/ray\", line 8, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/ray/scripts/scripts.py\", line 1989, in main\n",
      "    return cli()\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/click/core.py\", line 1128, in __call__\n",
      "    return self.main(*args, **kwargs)\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/click/core.py\", line 1053, in main\n",
      "    rv = self.invoke(ctx)\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/click/core.py\", line 1659, in invoke\n",
      "    return _process_result(sub_ctx.command.invoke(sub_ctx))\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/click/core.py\", line 1395, in invoke\n",
      "    return ctx.invoke(self.callback, **ctx.params)\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/click/core.py\", line 754, in invoke\n",
      "    return __callback(*args, **kwargs)\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/ray/scripts/scripts.py\", line 750, in start\n",
      "    node = ray.node.Node(\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/ray/node.py\", line 147, in __init__\n",
      "    session_name = self._internal_kv_get_with_retry(\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/ray/node.py\", line 1295, in _internal_kv_get_with_retry\n",
      "    raise RuntimeError(f\"Could not read '{key}' from GCS (redis). \"\n",
      "RuntimeError: Could not read 'b'session_name'' from GCS (redis). Has redis started correctly on the head node?\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "! ray start --address='172.31.51.124:6379' --redis-password='5241590000000000'\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/urllib3/connection.py\", line 174, in _new_conn\r\n",
      "    conn = connection.create_connection(\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/urllib3/util/connection.py\", line 96, in create_connection\r\n",
      "    raise err\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/urllib3/util/connection.py\", line 86, in create_connection\r\n",
      "    sock.connect(sa)\r\n",
      "ConnectionRefusedError: [Errno 111] Connection refused\r\n",
      "\r\n",
      "During handling of the above exception, another exception occurred:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 699, in urlopen\r\n",
      "    httplib_response = self._make_request(\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 394, in _make_request\r\n",
      "    conn.request(method, url, **httplib_request_kw)\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/urllib3/connection.py\", line 239, in request\r\n",
      "    super(HTTPConnection, self).request(method, url, body=body, headers=headers)\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/http/client.py\", line 1256, in request\r\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/http/client.py\", line 1302, in _send_request\r\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/http/client.py\", line 1251, in endheaders\r\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/http/client.py\", line 1011, in _send_output\r\n",
      "    self.send(msg)\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/http/client.py\", line 951, in send\r\n",
      "    self.connect()\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/urllib3/connection.py\", line 205, in connect\r\n",
      "    conn = self._new_conn()\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/urllib3/connection.py\", line 186, in _new_conn\r\n",
      "    raise NewConnectionError(\r\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fcb890277c0>: Failed to establish a new connection: [Errno 111] Connection refused\r\n",
      "\r\n",
      "During handling of the above exception, another exception occurred:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/requests/adapters.py\", line 439, in send\r\n",
      "    resp = conn.urlopen(\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 755, in urlopen\r\n",
      "    retries = retries.increment(\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/urllib3/util/retry.py\", line 574, in increment\r\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\r\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='172.31.51.124', port=20002): Max retries exceeded with url: /api/version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb890277c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\r\n",
      "\r\n",
      "During handling of the above exception, another exception occurred:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/ray/dashboard/modules/job/sdk.py\", line 95, in _check_connection_and_version\r\n",
      "    r = self._do_request(\"GET\", \"/api/version\")\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/ray/dashboard/modules/job/sdk.py\", line 123, in _do_request\r\n",
      "    return requests.request(\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/requests/api.py\", line 61, in request\r\n",
      "    return session.request(method=method, url=url, **kwargs)\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/requests/sessions.py\", line 542, in request\r\n",
      "    resp = self.send(prep, **send_kwargs)\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/requests/sessions.py\", line 655, in send\r\n",
      "    r = adapter.send(request, **kwargs)\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/requests/adapters.py\", line 516, in send\r\n",
      "    raise ConnectionError(e, request=request)\r\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.31.51.124', port=20002): Max retries exceeded with url: /api/version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb890277c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\r\n",
      "\r\n",
      "During handling of the above exception, another exception occurred:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/bin/torchx\", line 8, in <module>\r\n",
      "    sys.exit(main())\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/torchx/cli/main.py\", line 110, in main\r\n",
      "    run_main(get_sub_cmds(), argv)\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/torchx/cli/main.py\", line 106, in run_main\r\n",
      "    args.func(args)\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/torchx/cli/cmd_run.py\", line 204, in run\r\n",
      "    self._run(runner, args)\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/torchx/cli/cmd_run.py\", line 167, in _run\r\n",
      "    app_handle = runner.run_component(\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/torchx/runner/api.py\", line 136, in run_component\r\n",
      "    return self.schedule(dryrun_info)\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/torchx/runner/api.py\", line 208, in schedule\r\n",
      "    app_id = sched.schedule(dryrun_info)\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/torchx/schedulers/ray_scheduler.py\", line 160, in schedule\r\n",
      "    client: JobSubmissionClient = JobSubmissionClient(f\"http://{ip_address}\")\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/ray/dashboard/modules/job/sdk.py\", line 91, in __init__\r\n",
      "    self._check_connection_and_version()\r\n",
      "  File \"/home/ubuntu/anaconda3/envs/ray/lib/python3.8/site-packages/ray/dashboard/modules/job/sdk.py\", line 105, in _check_connection_and_version\r\n",
      "    raise ConnectionError(\r\n",
      "ConnectionError: Failed to connect to Ray at address: http://172.31.51.124:20002.\r\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "# Pick up the Ray dashboard address to execute a job against it\n",
    "# Provide a path to your working directory with dependencies along with the script you want to run\n",
    "! torchx run -s ray -cfg dashboard_address=172.31.51.124:20002,working_dir=. utils.binary --entrypoint ray_simple.py\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Hello torchX Ray scheduler\n",
    "\n",
    "The way the scheduler works is it either needs a dashboard address to point jobs or it can use your `ray_cluster.yaml` to identify your cluster. Once the cluster is setup you can use the `torchx` cli to submit jobs by specifying a `working_dir` with all your files and data and an an `entrypoint` for a binary script a.k.a your training script.\n",
    "\n",
    "After deploying a job you'll get a job ID and can use it to determine the status of your job and inspect its logs."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "! torchx run -s ray -cfg cluster_config_file=ray_cluster.yaml,working_dir=. utils.binary --entrypoint ray_simple.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Get a job ID from deployed job\n",
    "torchx run -s ray -cfg dashboard_address=34.209.89.185:20002,working_dir=test_dir utils.binary --entrypoint ray_simple.py\n",
    "\n",
    "# Job ID looks like etc..\n",
    "\n",
    "# Get a job status\n",
    "# PENDING, FAILED, INTERRUPTED ETC..\n",
    "torchx describe ray://torchx/34.209.89.185:20002-raysubmit_aKvezN3NyA2mqZeW\n",
    "\n",
    "# Get job logs\n",
    "# Aggregatee logs from all machinees in the same place\n",
    "torchx log ray://torchx/34.209.89.185:20002-raysubmit_aKvezN3NyA2mqZeW"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Writing a distributed PyTorch Script\n",
    "\n",
    "Unfortunately it's currently not possible to automagically make a PyTorch script distributed but it's not too complicated and we'll walk through the steps to do so right now.\n",
    "We're going to turn this example of a resnet training loop https://github.com/pytorch/examples/blob/master/mnist/main.py and use the Distributed Data Parallel version of it by github.com/yqhu"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Overwriting ddp_resnet_train.py\n"
     ]
    }
   ],
   "source": [
    "%%writefile ddp_resnet_train.py\n",
    "#!/usr/bin/env python3\n",
    "# Imports\n",
    "import os\n",
    "import argparse\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "import torch.optim as optim\n",
    "from torchvision import datasets, transforms\n",
    "from torch.optim.lr_scheduler import StepLR\n",
    "\n",
    "import torch.distributed as dist\n",
    "import torch.multiprocessing as mp\n",
    "from torch.nn.parallel import DistributedDataParallel as DDP\n",
    "from torch.utils.data.distributed import DistributedSampler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Appending to ddp_resnet_train.py\n"
     ]
    }
   ],
   "source": [
    "%%writefile ddp_resnet_train.py -a\n",
    "# Setup scripts to setup MASTER_ADDR AND MASTER_PORT\n",
    "# World size is the number of nodes in a distributed setting\n",
    "# Rank is the ID of a specific node in a distributed setting\n",
    "# Gloo is a popular backend for internode communication\n",
    "def setup(rank, world_size):\n",
    "    os.environ['MASTER_ADDR'] = 'localhost'\n",
    "    os.environ['MASTER_PORT'] = '12355'\n",
    "\n",
    "    # initialize the process group\n",
    "    backend = \"gloo\"\n",
    "    dist.init_process_group(backend=backend, init_method=f\"tcp://{master_addr}:{master_port}\", rank=rank, world_size=world_size)\n",
    "\n",
    "\n",
    "def cleanup():\n",
    "    dist.destroy_process_group()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "a = 2\n",
      "a = 2\n"
     ]
    }
   ],
   "source": [
    "! cat ddp_resnet_train.py"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}